# coding: utf-8

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Like(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, user_id: int=None, track_id: int=None, timestamp: str=None):  # noqa: E501
        """Like - a model defined in OpenAPI

        :param id: The id of this Like.  # noqa: E501
        :type id: int
        :param user_id: The user_id of this Like.  # noqa: E501
        :type user_id: int
        :param track_id: The track_id of this Like.  # noqa: E501
        :type track_id: int
        :param timestamp: The timestamp of this Like.  # noqa: E501
        :type timestamp: str
        """
        self.openapi_types = {
            'id': int,        # <--- CAMBIO: int
            'user_id': int,   # <--- CAMBIO: int
            'track_id': int,  # <--- CAMBIO: int
            'timestamp': str
        }

        self.attribute_map = {
            'id': 'id',
            'user_id': 'user_id',
            'track_id': 'track_id',
            'timestamp': 'timestamp'
        }

        self._id = id
        self._user_id = user_id
        self._track_id = track_id
        self._timestamp = timestamp

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Like':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The like of this Like.  # noqa: E501
        :rtype: Like
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Like.


        :return: The id of this Like.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Like.


        :param id: The id of this Like.
        :type id: int
        """

        self._id = id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Like.


        :return: The user_id of this Like.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Like.


        :param user_id: The user_id of this Like.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def track_id(self) -> int:
        """Gets the track_id of this Like.


        :return: The track_id of this Like.
        :rtype: int
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id: int):
        """Sets the track_id of this Like.


        :param track_id: The track_id of this Like.
        :type track_id: int
        """

        self._track_id = track_id

    @property
    def timestamp(self) -> str:
        """Gets the timestamp of this Like.


        :return: The timestamp of this Like.
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp: str):
        """Sets the timestamp of this Like.


        :param timestamp: The timestamp of this Like.
        :type timestamp: str
        """

        self._timestamp = timestamp