# coding: utf-8

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Recommendation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, user_id: int=None, track_id: int=None):  # noqa: E501
        """Recommendation - a model defined in OpenAPI

        :param user_id: The user_id of this Recommendation.  # noqa: E501
        :type user_id: int
        :param track_id: The track_id of this Recommendation.  # noqa: E501
        :type track_id: int
        """
        self.openapi_types = {
            'user_id': int,    # <--- CAMBIO: int
            'track_id': int    # <--- CAMBIO: int
        }

        self.attribute_map = {
            'user_id': 'user_id',
            'track_id': 'track_id'
        }

        self._user_id = user_id
        self._track_id = track_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Recommendation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The recommendation of this Recommendation.  # noqa: E501
        :rtype: Recommendation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Recommendation.


        :return: The user_id of this Recommendation.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Recommendation.


        :param user_id: The user_id of this Recommendation.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def track_id(self) -> int:
        """Gets the track_id of this Recommendation.


        :return: The track_id of this Recommendation.
        :rtype: int
        """
        return self._track_id

    @track_id.setter
    def track_id(self, track_id: int):
        """Sets the track_id of this Recommendation.


        :param track_id: The track_id of this Recommendation.
        :type track_id: int
        """

        self._track_id = track_id