# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class Track(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, album_id: int=None, title: str=None, duration: str=None, file_url: str=None, published_at: str=None):
        """Track - a model defined in OpenAPI

        :param id: The id of this Track.
        :type id: int
        :param album_id: The album_id of this Track.
        :type album_id: int
        :param title: The title of this Track.
        :type title: str
        :param duration: The duration of this Track.
        :type duration: str
        :param file_url: The file_url of this Track.
        :type file_url: str
        :param published_at: The published_at of this Track.
        :type published_at: str
        """
        self.openapi_types = {
            'id': int,       # <--- CAMBIO IMPORTANTE: Ahora es int
            'album_id': int, # <--- CAMBIO IMPORTANTE: Ahora es int
            'title': str,
            'duration': str,
            'file_url': str,
            'published_at': str
        }

        self.attribute_map = {
            'id': 'id',
            'album_id': 'album_id',
            'title': 'title',
            'duration': 'duration',
            'file_url': 'file_url',
            'published_at': 'published_at'
        }

        self._id = id
        self._album_id = album_id
        self._title = title
        self._duration = duration
        self._file_url = file_url
        self._published_at = published_at

    @classmethod
    def from_dict(cls, dikt: dict) -> 'Track':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The track of this Track.
        :rtype: Track
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Track.

        :return: The id of this Track.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Track.

        :param id: The id of this Track.
        :type id: int
        """
        self._id = id

    @property
    def album_id(self) -> int:
        """Gets the album_id of this Track.

        :return: The album_id of this Track.
        :rtype: int
        """
        return self._album_id

    @album_id.setter
    def album_id(self, album_id: int):
        """Sets the album_id of this Track.

        :param album_id: The album_id of this Track.
        :type album_id: int
        """
        self._album_id = album_id

    @property
    def title(self) -> str:
        """Gets the title of this Track.

        :return: The title of this Track.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Track.

        :param title: The title of this Track.
        :type title: str
        """
        self._title = title

    @property
    def duration(self) -> str:
        """Gets the duration of this Track.

        :return: The duration of this Track.
        :rtype: str
        """
        return self._duration

    @duration.setter
    def duration(self, duration: str):
        """Sets the duration of this Track.

        :param duration: The duration of this Track.
        :type duration: str
        """
        self._duration = duration

    @property
    def file_url(self) -> str:
        """Gets the file_url of this Track.

        :return: The file_url of this Track.
        :rtype: str
        """
        return self._file_url

    @file_url.setter
    def file_url(self, file_url: str):
        """Sets the file_url of this Track.

        :param file_url: The file_url of this Track.
        :type file_url: str
        """
        self._file_url = file_url

    @property
    def published_at(self) -> str:
        """Gets the published_at of this Track.

        :return: The published_at of this Track.
        :rtype: str
        """
        return self._published_at

    @published_at.setter
    def published_at(self, published_at: str):
        """Sets the published_at of this Track.

        :param published_at: The published_at of this Track.
        :type published_at: str
        """
        self._published_at = published_at